#ifndef HAL_CONFIG_H
#define HAL_CONFIG_H

#include "em_device.h"
#include "hal-config-types.h"

// This file is auto-generated by Hardware Configurator in Simplicity Studio.
// Any content between $[ and ]$ will be replaced whenever the file is regenerated.
// Content outside these regions will be preserved.

// $[ACMP0]
// [ACMP0]$

// $[ADC0]
// [ADC0]$

// $[BTL_BUTTON]
// [BTL_BUTTON]$

// $[BUTTON]
// [BUTTON]$

// $[CMU]
#define HAL_CLK_HFCLK_SOURCE                 (HAL_CLK_HFCLK_SOURCE_HFRCO)
#define HAL_CLK_LFACLK_SOURCE                (HAL_CLK_LFCLK_SOURCE_DISABLED)
#define HAL_CLK_LFBCLK_SOURCE                (HAL_CLK_LFCLK_SOURCE_DISABLED)
#define HAL_CLK_LFCCLK_SOURCE                (HAL_CLK_LFCLK_SOURCE_DISABLED)
#define BSP_CLK_HFXO_PRESENT                 (0)
#define BSP_CLK_HFXO_FREQ                    (24000000UL)
#define BSP_CLK_HFXO_INIT                     CMU_HFXOINIT_DEFAULT
#define BSP_CLK_HFXO_BOOST                   (_CMU_CTRL_HFXOBOOST_100PCENT)
#define BSP_CLK_LFXO_PRESENT                 (0)
#define BSP_CLK_LFXO_INIT                     CMU_LFXOINIT_DEFAULT
#define BSP_CLK_LFXO_FREQ                    (32768U)
#define BSP_CLK_LFXO_BOOST                   (0)
// [CMU]$

// $[EMU]
// [EMU]$

// $[EXTFLASH]
// [EXTFLASH]$

// $[GPIO]
#define PORTIO_GPIO_SWCLK_PIN                (0U)
#define PORTIO_GPIO_SWCLK_PORT               (gpioPortF)
#define PORTIO_GPIO_DBGROUTE_LOC             (0U)

#define PORTIO_GPIO_SWDIO_PIN                (1U)
#define PORTIO_GPIO_SWDIO_PORT               (gpioPortF)

// [GPIO]$

// $[I2C0]
// [I2C0]$

// $[I2CSENSOR]
// [I2CSENSOR]$

// $[IDAC0]
// [IDAC0]$

// $[IOEXP]
// [IOEXP]$

// $[LED]
// [LED]$

// $[LEUART0]
// [LEUART0]$

// $[LFXO]
// [LFXO]$

// $[MSC]
// [MSC]$

// $[PCNT0]
// [PCNT0]$

// $[PORTIO]
// [PORTIO]$

// $[PRS]
// [PRS]$

// $[SERIAL]
#define BSP_SERIAL_APP_PORT                  (HAL_SERIAL_PORT_USART1)
#define BSP_SERIAL_APP_TX_PIN                (7U)
#define BSP_SERIAL_APP_TX_PORT               (gpioPortD)
#define BSP_SERIAL_APP_ROUTE_LOC             (3U)

#define BSP_SERIAL_APP_RX_PIN                (6U)
#define BSP_SERIAL_APP_RX_PORT               (gpioPortD)

#define HAL_SERIAL_APP_BAUD_RATE             (115200UL)
#define HAL_SERIAL_APP_FLOW_CONTROL          (HAL_USART_FLOW_CONTROL_NONE)
// [SERIAL]$

// $[SPIDISPLAY]
// [SPIDISPLAY]$

// $[SPINCP]
// [SPINCP]$

// $[TIMER0]
// [TIMER0]$

// $[TIMER1]

// [TIMER1]$

// $[TIMER2]

// [TIMER2]$

// $[UARTNCP]
// [UARTNCP]$

// $[USART0]
// [USART0]$

// $[USART1]
#define PORTIO_USART1_RX_PIN                 (6U)
#define PORTIO_USART1_RX_PORT                (gpioPortD)
#define PORTIO_USART1_ROUTE_LOC              (2U)

#define PORTIO_USART1_TX_PIN                 (7U)
#define PORTIO_USART1_TX_PORT                (gpioPortD)

#define HAL_USART1_ENABLE                    (1)

#define BSP_USART1_TX_PIN                    (7U)
#define BSP_USART1_TX_PORT                   (gpioPortD)
#define BSP_USART1_ROUTE_LOC                 (2U)

#define BSP_USART1_RX_PIN                    (6U)
#define BSP_USART1_RX_PORT                   (gpioPortD)

#define HAL_USART1_BAUD_RATE                 (115200UL)
#define HAL_USART1_FLOW_CONTROL              (HAL_USART_FLOW_CONTROL_NONE)
// [USART1]$

// $[USB]
// [USB]$

// $[VCOM]
// [VCOM]$

// $[WDOG]
// [WDOG]$

#if defined(_SILICON_LABS_MODULE)
#include "sl_module.h"
#endif

#endif /* HAL_CONFIG_H */

// $[Custom pin names]
#define led0r_PIN                            (14U)
#define led0r_PORT                           (gpioPortB)

#define led1r_PIN                            (0U)
#define led1r_PORT                           (gpioPortA)

#define led0g_PIN                            (15U)
#define led0g_PORT                           (gpioPortC)

#define led1g_PIN                            (13U)
#define led1g_PORT                           (gpioPortE)

#define led0b_PIN                            (11U)
#define led0b_PORT                           (gpioPortB)

#define led1b_PIN                            (13U)
#define led1b_PORT                           (gpioPortB)

#define touch0_PIN                           (0U)
#define touch0_PORT                          (gpioPortC)

#define touch1_PIN                           (1U)
#define touch1_PORT                          (gpioPortC)

#define txen_PIN                             (14U)
#define txen_PORT                            (gpioPortC)

#define relay0_PIN                           (12U)
#define relay0_PORT                          (gpioPortE)

#define relay1_PIN                           (2U)
#define relay1_PORT                          (gpioPortF)
// [Custom pin names]$

